### ISSUE TITLE
Problem with updates using Yarn

### ISSUE THREAD

**Issue by inoyakaigor** [Pilaton/vscode-npm-lens-support#3]
I've ran into a problem with upgrade deps with Yarn
![image](https://github.com/Pilaton/vscode-npm-lens-support/assets/1235286/99ea7373-9242-47cf-8545-92980c2cd5b2)

Windows 11
Nodejs 21
Yarn 4.1.1

**Comment by Pilaton** [comment]
Fixed the problem. It will be resolved in the next update. Thanks
