### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by guotingchao** [Pilaton/vscode-npm-lens-support#4]
Hi, this is a very nice plugin, beautiful and intuitive.

However, I would suggest to consider removing the Hello view that opens in the menu bar and just keep the right side window for managing dependencies.
<img width="357" alt="image" src="https://github.com/user-attachments/assets/a0221206-998d-40d8-bcfa-b53468083968" />

 I'm not sure if there are some limitations in vscode that make you do this, it would be great if it works.

**Comment by Pilaton** [comment]
Hi! This is due to a limitation in VSCode.

**Comment by guotingchao** [comment]
> Hi! This is due to a limitation in VSCode.

Okay, I get it. :)
It's true that we can't change it for the time being.
